import XCTest
@testable import BiomedShelfScanner

/// Validates `ShelfOrder` against golden vectors generated by its JavaScript twin.
///
/// Regenerate the fixture from the repo root with:
///   node ios/Tools/shelfOrderGolden.js biomed-shelf-ranges.json ios/Tests/ShelfOrderGolden.json
///
/// `ios/Tools/shelforder.test.js` is the faster loop and carries far more cases, including a
/// ten-thousand-row false-positive floor. What *this* file is for is parity: that the Swift and
/// the JS answer identically. When they disagree, the JS is not automatically right — but the
/// disagreement is always a bug in one of them, and shipping while they differ means the offline
/// tuning loop is measuring something the app does not do.
final class ShelfOrderTests: XCTestCase {

    struct Golden: Decodable {
        struct Pair: Decodable { let a: String; let b: String; let cmp: Int }
        struct Sequence: Decodable {
            let name: String
            let spines: [String?]
            let verdicts: [String]
            let edge: [Bool]
            let anchored: [Bool]
        }
        struct Face: Decodable { let lvl: Int; let id: String; let side: String }
        struct FaceCase: Decodable { let cn: String; let faces: [Face] }

        let trailers: [Pair]
        let sequences: [Sequence]
        let faces: [FaceCase]
    }

    lazy var golden: Golden = {
        let url = Bundle(for: Self.self).url(forResource: "ShelfOrderGolden", withExtension: "json")!
        return try! JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }()

    // MARK: - Ordering

    /// The reason this module exists. Every pair here is one `CallNumber.compare` answers wrongly
    /// — `no.9` after `no.10`, `no.66` before `no.7` — plus enough base-comparator cases to catch
    /// a port that fixed trailers by breaking decimal cutters.
    func testTrailerOrderingMatchesJS() {
        for p in golden.trailers {
            guard let a = ShelfOrder.key(p.a), let b = ShelfOrder.key(p.b) else {
                return XCTFail("failed to key \(p.a) / \(p.b)")
            }
            XCTAssertEqual(ShelfOrder.compare(a, b), p.cmp, "compare(\(p.a), \(p.b))")
        }
    }

    /// All three spellings a spine label can produce for one physical volume are the same book.
    /// OCR returns whichever it feels like, frame to frame, on the same label.
    func testVolumeSpellingsAreEquivalent() throws {
        let forms = ["W1 NA388 no.66", "W1 NA388 NO66", "W1 NA388 no 66", "W1 NA388 NO. 66"]
        let keys = try forms.map { try XCTUnwrap(ShelfOrder.key($0), $0) }
        for k in keys.dropFirst() {
            XCTAssertEqual(ShelfOrder.compare(keys[0], k), 0, "\(k.raw) should equal \(keys[0].raw)")
        }
    }

    /// Trailers come off the end without taking any of the base with them. The `> 2` floor is
    /// load-bearing: without it, NLM `W 2000` loses its class number to the year pattern and lands
    /// on a different floor.
    func testTrailerSplitLeavesTheBaseIntact() throws {
        let cases: [(String, String, Int)] = [
            ("W1 NA388", "W1 NA388", 0),
            ("W1 NA388 no.66 1984", "W1 NA388", 2),
            ("WM 13 D5537 1984", "WM 13 D5537", 1),
            ("W4C Z89P 2009", "W4C Z89P", 1),
            ("W 2000", "W 2000", 0),
        ]
        for (input, base, count) in cases {
            let k = try XCTUnwrap(ShelfOrder.key(input), input)
            XCTAssertEqual(k.trailers.count, count, "trailer count for \(input)")
            XCTAssertEqual(CallNumber.compare(k.base, try XCTUnwrap(CallNumber.parse(base))), 0,
                           "base for \(input) should be \(base)")
        }
    }

    // MARK: - Verdicts

    /// Whole rows, one per guard. A failure names the rule that broke rather than leaving you to
    /// work out which of thirteen shelves went wrong.
    func testSequenceVerdictsMatchJS() {
        for seq in golden.sequences {
            let spines = seq.spines.enumerated().map { i, cn in
                ShelfOrder.Spine(callNumber: cn, anchored: seq.anchored[i], edge: seq.edge[i])
            }
            let got = ShelfOrder.judge(spines, expected: nil).map(Self.name)
            XCTAssertEqual(got, seq.verdicts, seq.name)
        }
    }

    /// The mis-blame this whole approach exists to avoid, stated once on its own so it cannot be
    /// lost in a fixture regeneration: adjacent-pair comparison flags (F, D), which accuses D
    /// exactly as loudly as it accuses F. Only F moved.
    func testOutOfOrderBlamesOneBook() {
        let row = ["W1 AA100", "W1 BB100", "W1 FF100", "W1 DD100", "W1 EE100"]
        let got = ShelfOrder.judge(row.map { ShelfOrder.Spine(callNumber: $0) }, expected: nil)
        XCTAssertEqual(got.map(Self.name), ["ok", "ok", "outOfOrder", "ok", "ok"])
    }

    /// A correctly ordered shelf must produce nothing. This is the failure that costs trust: a
    /// librarian sent to reshelve a book that was already in the right place.
    func testCorrectShelvesAreNeverFlagged() {
        let rows = [
            ["W1 AA100", "W1 BB100", "W1 CC100", "W1 DD100"],
            ["W1 NA388 no.1", "W1 NA388 no.2", "W1 NA388 no.10", "W1 NA388 no.11"],
            ["W1 AA100", "W1 AA100", "W1 BB100", "W1 BB100"],
        ]
        for row in rows {
            let got = ShelfOrder.judge(row.map { ShelfOrder.Spine(callNumber: $0) }, expected: nil)
            XCTAssertFalse(got.contains { $0.isMisfile }, "\(row) should be clean")
        }
    }

    // MARK: - Wrong shelf

    /// Wrong-shelf detection runs against the real dataset, and it uses `Router.search` rather
    /// than `Router.locate` on purpose: `locate` returns only the lowest containing face, and 262
    /// of 652 cases in this fixture are contained by more than one. Judging against the lowest
    /// alone would flag whole serial runs as misfiled.
    func testBooksAreAtHomeOnEveryFaceThatContainsThem() throws {
        let router = try Router(bundledRanges: "biomed-shelf-ranges")
        let search: (CallNumber) -> [ShelfOrder.Face] = { router.search($0).map(ShelfOrder.Face.init) }

        var seams = 0
        for c in golden.faces where c.faces.count > 1 {
            seams += 1
            for f in c.faces {
                let face = ShelfOrder.Face(level: f.lvl, shelfID: f.id, side: f.side)
                let got = ShelfOrder.judge([ShelfOrder.Spine(callNumber: c.cn)],
                                           expected: face, search: search)
                XCTAssertFalse(got[0].isMisfile, "\(c.cn) should be at home on \(f.lvl)|\(f.id)|\(f.side)")
            }
        }
        XCTAssertGreaterThan(seams, 100, "the fixture should still be full of seam cases")
    }

    func testABookOffItsFaceIsFlagged() throws {
        let router = try Router(bundledRanges: "biomed-shelf-ranges")
        let search: (CallNumber) -> [ShelfOrder.Face] = { router.search($0).map(ShelfOrder.Face.init) }

        // Well-formed as well as locatable. The fixture is built from `Object.values(DATA)`, so its
        // order is the range file's key order, and five of its rows are call numbers `isWellFormed`
        // deliberately rejects while `Router.search` still places them (`Q 41 R81R8`,
        // `WC 160 G7.78T`, `WX 27 GF7 P3R5D`, …). Index 0 was a usable row only by luck; a
        // re-export that reordered the ranges file would have made `judge` return `.unknown` here
        // and failed this test for a reason that has nothing to do with the code.
        let c = try XCTUnwrap(golden.faces.first {
            !$0.faces.isEmpty && CallNumber.parse($0.cn)?.isWellFormed == true
        })
        let home = c.faces[0]
        let elsewhere = ShelfOrder.Face(level: home.lvl == 11 ? 1 : 11, shelfID: "no-such-shelf", side: "a")

        let got = ShelfOrder.judge([ShelfOrder.Spine(callNumber: c.cn)],
                                   expected: elsewhere, search: search)
        guard case .wrongShelf = got[0] else {
            return XCTFail("\(c.cn) should be wrongShelf when read at \(elsewhere)")
        }
    }

    /// Shelf ranges are broad intervals, so nearly any string falls inside *some* range — `W1
    /// ZZZ999` locates happily, which is why `isWellFormed` exists separately from `Router.locate`.
    /// The guard under test is what happens when the lookup genuinely comes back empty: Reference
    /// and unmapped stacks exist, and this app does not know about them.
    func testAnUnlocatableBookIsNeverWrongShelf() {
        let elsewhere = ShelfOrder.Face(level: 11, shelfID: "bot-1", side: "a")
        let got = ShelfOrder.judge([ShelfOrder.Spine(callNumber: "W1 NA388 no.66 1984")],
                                   expected: elsewhere, search: { _ in [] })
        XCTAssertFalse(got[0].isMisfile)
    }

    /// `judge` and `inferFace` have to ask the face lookup about the same key, and it has to be the
    /// base. Searched raw, `W1 DE244 no.1` is contained by one face and `W1 DE244` by two — the two
    /// keys disagree for 1224 of the 1600 volume numbers the range data can build, so a serial run
    /// judged on raw numbers can straddle a boundary and report half of itself as misfiled.
    ///
    /// Asserted by spying on the closure rather than through the golden fixture, which cannot see
    /// it: every `sequences` entry is generated with no `expected`, so the wrong-shelf branch is
    /// never compared across the two implementations.
    func testTheFaceLookupIsAskedAboutTheBase() {
        var asked: [String] = []
        let spy: (CallNumber) -> [ShelfOrder.Face] = { asked.append($0.raw); return [] }

        _ = ShelfOrder.judge([ShelfOrder.Spine(callNumber: "W1 NA388 no.66 1984")],
                             expected: ShelfOrder.Face(level: 11, shelfID: "bot-1", side: "a"),
                             search: spy)
        XCTAssertEqual(asked, ["W1 NA388"], "judge should search the base, not the volume")

        asked = []
        _ = ShelfOrder.inferFace(["W1 NA388 no.1", "W1 NA388 no.2", "W1 NA388 no.3"], search: spy)
        XCTAssertEqual(asked, ["W1 NA388", "W1 NA388", "W1 NA388"],
                       "inferFace should search the same key judge does")
    }

    /// Both twins have to break an exact scheme tie the same way, or a face straddling the
    /// W1-serials / NLM-monograph boundary excludes opposite halves on device and in the offline
    /// tools. Ranked, and w1 wins.
    func testAnEvenSchemeSplitKeepsTheW1Books() {
        let spines = ["W1 AA100", "W1 BB100", "WM 13 D5537", "WM 14 D5537"]
            .map { ShelfOrder.Spine(callNumber: $0) }
        XCTAssertEqual(ShelfOrder.judge(spines, expected: nil).map(Self.name),
                       ["ok", "ok", "unknown", "unknown"])
    }

    /// `minSpines: 0` means no floor. The JS twin wrote this as `opts.minSpines || 3`, which
    /// rewrote a caller's 0 to 3 while these real default arguments honoured it.
    func testACallerAskingForNoFloorGetsNoFloor() throws {
        let router = try Router(bundledRanges: "biomed-shelf-ranges")
        let search: (CallNumber) -> [ShelfOrder.Face] = { router.search($0).map(ShelfOrder.Face.init) }
        let c = try XCTUnwrap(golden.faces.first {
            !$0.faces.isEmpty && CallNumber.parse($0.cn)?.isWellFormed == true
        })
        XCTAssertNotNil(ShelfOrder.inferFace([c.cn, c.cn], search: search, minSpines: 0))
        XCTAssertNotNil(ShelfOrder.inferFace([c.cn, c.cn], search: search,
                                             minSpines: 2, minAgreement: 0))
    }

    // MARK: - Inferring the face

    func testFaceIsInferredFromAMajorityAndNotFromTwoBooks() throws {
        let router = try Router(bundledRanges: "biomed-shelf-ranges")
        let search: (CallNumber) -> [ShelfOrder.Face] = { router.search($0).map(ShelfOrder.Face.init) }

        // Well-formed as well as locatable. The fixture is built from `Object.values(DATA)`, so its
        // order is the range file's key order, and five of its rows are call numbers `isWellFormed`
        // deliberately rejects while `Router.search` still places them (`Q 41 R81R8`,
        // `WC 160 G7.78T`, `WX 27 GF7 P3R5D`, …). Index 0 was a usable row only by luck; a
        // re-export that reordered the ranges file would have made `judge` return `.unknown` here
        // and failed this test for a reason that has nothing to do with the code.
        let c = try XCTUnwrap(golden.faces.first {
            !$0.faces.isEmpty && CallNumber.parse($0.cn)?.isWellFormed == true
        })
        let three = [c.cn, c.cn, c.cn]
        let guess = ShelfOrder.inferFace(three, search: search)
        XCTAssertNotNil(guess, "three books off one face should infer a face")
        if let guess {
            XCTAssertTrue(c.faces.contains { $0.lvl == guess.face.level && $0.id == guess.face.shelfID
                                             && $0.side == guess.face.side },
                          "the guess should be a face those books are actually on")
        }
        XCTAssertNil(ShelfOrder.inferFace([c.cn, c.cn], search: search),
                     "two books are below the floor — no guess is better than a coin flip")
    }

    // MARK: -

    /// Verdict names, matching the JS twin's strings. Kept as one function so a renamed case is a
    /// compile error here rather than a silent fixture mismatch.
    private static func name(_ v: ShelfOrder.Verdict) -> String {
        switch v {
        case .ok:           return "ok"
        case .outOfOrder:   return "outOfOrder"
        case .wrongShelf:   return "wrongShelf"
        case .volumeBreak:  return "volumeBreak"
        case .unknown:      return "unknown"
        case .unanchored:   return "unanchored"
        }
    }
}
